name: PR Branch Build and Test

on:
  push:
    branches-ignore:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    name: Node.JS ${{ matrix.node-version }}
    strategy:
      matrix:
        node-version: [10.x, 12.x, 14.x]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install
        run: yarn install
      - name: Test
        env:
          DEBUG: lambda-tools:*
          HOST_TMP_FOLDER: "./"
        run: yarn test
      - name: Coverage
        run: yarn coverage
